# codemagic.yaml (configurat pentru a crea un .ipa pentru AltStore)

workflows:
  build-unsigned-ipa:
    name: Build Unsigned IPA for AltStore
    instance_type: mac_mini_m1
    
    # Nu avem nevoie de integrare cu App Store Connect aici
    
    environment:
      vars:
        IOS_PROJECT: 'obs-ios-camera-source.xcodeproj'
        IOS_SCHEME: 'obs-ios-camera-source'

    scripts:
      - name: Build unsigned .app bundle
        script: | 
          # Construim aplicatia pentru o arhitectura reala, dar fara a o semna
          xcodebuild build -project "$IOS_PROJECT" \
                           -scheme "$IOS_SCHEME" \
                           -sdk iphoneos \
                           -configuration Release \
                           CODE_SIGN_IDENTITY="" \
                           CODE_SIGNING_REQUIRED=NO \
                           CODE_SIGNING_ALLOWED=NO

      - name: Create unsigned .ipa
        script: | 
          # Acest script ia rezultatul build-ului (.app) si il impacheteaza intr-un .ipa
          set -e # Opreste scriptul daca o comanda esueaza
          echo "Finding .app bundle..."
          # Gaseste calea catre folderul build/Release-iphoneos
          BUILD_DIR=$(find $CM_BUILD_DIR/build -type d -name "Release-iphoneos")
          APP_PATH=$(find "$BUILD_DIR" -type d -name "*.app" | head -n 1)
          
          if [ -z "$APP_PATH" ]; then
            echo "Error: .app bundle not found!"
            exit 1
          fi
          
          echo ".app bundle found at: $APP_PATH"
          
          # Creeaza structura necesara pentru .ipa
          echo "Creating Payload directory..."
          mkdir -p Payload
          echo "Copying .app to Payload..."
          cp -R "$APP_PATH" Payload/
          
          # Arhiveaza folderul Payload intr-un fisier .ipa
          echo "Creating .ipa file..."
          zip -r "Unsigned_App.ipa" Payload
          
          echo "Unsigned .ipa created successfully!"

    artifacts:
      - ./*.ipa
