# codemagic.yaml (Versiune Corectată)

workflows:
  ios-app-build:
    name: iOS App Build
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: YOUR_APP_STORE_CONNECT_INTEGRATION_NAME # Înlocuiește cu numele integrării tale

    environment:
      # Variabilele personalizate trebuie să fie într-un grup 'vars'
      vars:
        IOS_PROJECT: 'obs-ios-camera-source.xcodeproj'
        IOS_SCHEME: 'obs-ios-camera-source'
      
      # Poți adăuga și grupuri specifice Xcode aici dacă este necesar
      # xcode:
      #   version: latest

    scripts:
      - name: Set up code signing settings
        script: | 
          xcode-project use-profiles

      - name: Increment build number
        script: | 
          # Folosește variabila de sistem a Codemagic pentru build number
          agvtool new-version -all $(($CM_BUILD_NUMBER + 1))

      - name: Build ipa for distribution
        script: | 
          # Folosește variabilele definite mai sus în grupul 'vars'
          xcode-project build-ipa \
            --project "$IOS_PROJECT" \
            --scheme "$IOS_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Logs/Build/*.xcactivitylog

    publishing:
      email:
        recipients:
          - you@example.com # Înlocuiește cu email-ul tău
        notify:
          success: true
          failure: true
